name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake files
        uses: Platane/snk@v3
        with:
          github_user_name: Shahzaib-arch786
          outputs: dist/snake.svg

      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
